#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="sites.service"

echo "Requesting sudo privileges to enable linger"
sudo loginctl enable-linger $USER

rm -rf env
python3 -m venv env
. env/bin/activate
pip install styledown

mkdir -p ~/.config/systemd/user

read -p "Enter the port for the service [2000]: " PORT
PORT=${PORT:-2000}

sed "s/PORT/$PORT/g" "$SERVICE_NAME" > ~/.config/systemd/user/"$SERVICE_NAME"
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE_NAME"
systemctl --user restart "$SERVICE_NAME"

echo "Installed and started $SERVICE_NAME"
