links:
  - label: Hikaru Analytics
    url: https://analytics.hikaru.org
    description: A simple privacy-first analytics platform.

  - label: Plastic Adrift
    url: https://plasticadrift.org
    description: >
      Interactive ocean-current visualization showing where floating plastic
      debris is likely to accumulate over time based on drift simulations and
      ocean circulation patterns.

  - label: YAML to Resume
    url: https://resume.hikaru.org
    description: >
      A simple, web-based tool to generate ATS-friendly PDF resumes from YAML
      files.

  - label: Loan Timeline
    url: https://github.com/mizuki-hikaru/loan-timeline
    description: >
      CLI tool that calculates how soon you will have your loan repayed.
